# Generated by Django 3.1.4 on 2020-12-30 04:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('longitude', models.FloatField(null=True, verbose_name='Longitud')),
                ('latitude', models.FloatField(null=True, verbose_name='Latitud')),
                ('geo_state', models.BooleanField(default=False, null=True, verbose_name='Estadogeo')),
            ],
            options={
                'verbose_name': 'GeoUsuario',
                'verbose_name_plural': 'GeoUsuarios',
                'ordering': ['-created'],
            },
        ),
    ]
